/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frame;

import DB.ConexaoBancoDeDados;
import Tela.Pessoa;
import Tela.rg;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public class Jpanel extends javax.swing.JPanel {

    /** Creates new form Jpanel */
    public Jpanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nome = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        data_nc = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        cpf = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        rg = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        n_mae = new javax.swing.JTextPane();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        n_pai = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        nome1 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPane16 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        nt = new javax.swing.JTextPane();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 0, 0));

        label1.setBackground(new java.awt.Color(255, 0, 0));
        label1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 0));
        label1.setText("Formulario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 772, 56);

        jLabel3.setText("Nippoflex                                                  Dados Pessoais                                   Elimflex            ");
        add(jLabel3);
        jLabel3.setBounds(0, 70, 762, 25);

        jLabel4.setText("Nome:");
        add(jLabel4);
        jLabel4.setBounds(0, 133, 35, 14);

        jScrollPane3.setViewportView(nome);

        add(jScrollPane3);
        jScrollPane3.setBounds(50, 70, 130, 22);

        jScrollPane4.setViewportView(data_nc);

        add(jScrollPane4);
        jScrollPane4.setBounds(447, 133, 136, 22);

        jScrollPane5.setViewportView(jTextPane5);

        add(jScrollPane5);
        jScrollPane5.setBounds(169, 192, 38, 22);

        jScrollPane6.setViewportView(jTextPane6);

        add(jScrollPane6);
        jScrollPane6.setBounds(83, 161, 246, 22);

        jLabel5.setText("Nacionalidade:");
        add(jLabel5);
        jLabel5.setBounds(0, 161, 70, 14);

        jLabel6.setText("Orgão Emissor:");
        add(jLabel6);
        jLabel6.setBounds(0, 192, 73, 14);

        jScrollPane7.setViewportView(jTextPane7);

        add(jScrollPane7);
        jScrollPane7.setBounds(626, 161, 126, 22);

        jScrollPane8.setViewportView(jTextPane8);

        add(jScrollPane8);
        jScrollPane8.setBounds(100, 370, 93, 20);

        jScrollPane9.setViewportView(jTextPane9);

        add(jScrollPane9);
        jScrollPane9.setBounds(40, 290, 250, 20);

        jLabel7.setText("Data de Nascimento:");
        add(jLabel7);
        jLabel7.setBounds(343, 133, 100, 14);

        jLabel8.setText("CPF:");
        add(jLabel8);
        jLabel8.setBounds(587, 133, 35, 14);

        jScrollPane10.setViewportView(cpf);

        add(jScrollPane10);
        jScrollPane10.setBounds(626, 133, 136, 22);

        jLabel9.setText("RG:");
        add(jLabel9);
        jLabel9.setBounds(343, 161, 35, 14);

        jScrollPane11.setViewportView(rg);

        add(jScrollPane11);
        jScrollPane11.setBounds(368, 161, 140, 22);

        jLabel10.setText("Data de Emissão:");
        add(jLabel10);
        jLabel10.setBounds(512, 161, 83, 14);

        jLabel11.setText("UF:");
        add(jLabel11);
        jLabel11.setBounds(148, 192, 17, 14);

        jScrollPane12.setViewportView(jTextPane12);

        add(jScrollPane12);
        jScrollPane12.setBounds(83, 192, 55, 22);

        jLabel13.setText("País Documento:");
        add(jLabel13);
        jLabel13.setBounds(243, 189, 94, 14);

        jLabel14.setText("Naturalidade:");
        add(jLabel14);
        jLabel14.setBounds(510, 189, 65, 14);

        jLabel15.setText("UF:");
        add(jLabel15);
        jLabel15.setBounds(682, 189, 17, 14);

        jScrollPane13.setViewportView(jTextPane13);

        add(jScrollPane13);
        jScrollPane13.setBounds(703, 189, 33, 22);

        jLabel16.setText("Nome da Mãe:");
        add(jLabel16);
        jLabel16.setBounds(0, 228, 69, 14);

        jLabel17.setText("Nome da Pai:");
        add(jLabel17);
        jLabel17.setBounds(0, 248, 63, 14);

        jLabel18.setText("Endereço:");
        add(jLabel18);
        jLabel18.setBounds(0, 268, 49, 14);

        jLabel19.setText("Tipo de Residência:   1 - Própria                                            2 - Alugada                                        3 - Com Parentes                                                 4 - Funcional ");
        add(jLabel19);
        jLabel19.setBounds(0, 328, 772, 14);

        jLabel20.setText("Bairro:");
        add(jLabel20);
        jLabel20.setBounds(0, 288, 32, 14);

        jLabel21.setText("CEP:");
        add(jLabel21);
        jLabel21.setBounds(0, 308, 23, 14);

        jLabel22.setText("Fone Res: ( )");
        add(jLabel22);
        jLabel22.setBounds(526, 228, 69, 14);

        jLabel23.setText("Cel: ( )");
        add(jLabel23);
        jLabel23.setBounds(473, 248, 69, 14);

        jLabel25.setText("Nº");
        add(jLabel25);
        jLabel25.setBounds(493, 268, 69, 14);

        jLabel26.setText("Complemento:");
        add(jLabel26);
        jLabel26.setBounds(667, 268, 69, 14);

        jLabel27.setText("Cidade:");
        add(jLabel27);
        jLabel27.setBounds(382, 288, 69, 14);

        jLabel29.setText("UF:");
        add(jLabel29);
        jLabel29.setBounds(193, 308, 17, 14);

        jLabel30.setText("Tempo de residencia:");
        add(jLabel30);
        jLabel30.setBounds(349, 308, 102, 14);

        jLabel24.setText("Valor do Patrimonio: R$");
        add(jLabel24);
        jLabel24.setBounds(650, 308, 112, 14);

        jScrollPane14.setViewportView(jTextPane14);

        add(jScrollPane14);
        jScrollPane14.setBounds(364, 190, 140, 22);

        jScrollPane15.setViewportView(n_mae);

        add(jScrollPane15);
        jScrollPane15.setBounds(73, 220, 250, 22);

        jLabel28.setText("                                                                                                                 Dados Profissionais");
        add(jLabel28);
        jLabel28.setBounds(0, 348, 762, 14);

        jLabel31.setText("Nome da Empresa:");
        add(jLabel31);
        jLabel31.setBounds(530, 370, 90, 14);

        jLabel32.setText("Endereço Comercial:");
        add(jLabel32);
        jLabel32.setBounds(0, 388, 98, 14);

        jLabel33.setText("Bairro:");
        add(jLabel33);
        jLabel33.setBounds(0, 408, 32, 14);

        jLabel34.setText("UF:");
        add(jLabel34);
        jLabel34.setBounds(0, 428, 17, 14);

        jLabel35.setText("Renda Mensal:");
        add(jLabel35);
        jLabel35.setBounds(0, 520, 71, 14);

        jLabel36.setText("Tipo de Compre. de Renda: 1 - Holerite                       2 - Extrato Bancario                             3 - Outros");
        add(jLabel36);
        jLabel36.setBounds(0, 490, 510, 14);

        jLabel37.setText("Renda Mensal:");
        add(jLabel37);
        jLabel37.setBounds(0, 448, 71, 14);

        jLabel38.setText("Nome da Empresa:");
        add(jLabel38);
        jLabel38.setBounds(0, 372, 90, 10);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(290, 530, 90, 23);

        jButton2.setText("Cancel");
        add(jButton2);
        jButton2.setBounds(373, 530, 110, 23);

        jScrollPane16.setViewportView(n_pai);

        add(jScrollPane16);
        jScrollPane16.setBounds(73, 248, 250, 20);

        jScrollPane17.setViewportView(nome1);

        add(jScrollPane17);
        jScrollPane17.setBounds(49, 133, 288, 22);

        jScrollPane18.setViewportView(jTextPane11);

        add(jScrollPane18);
        jScrollPane18.setBounds(270, 70, 80, 22);

        jScrollPane19.setViewportView(jTextPane16);

        add(jScrollPane19);
        jScrollPane19.setBounds(420, 70, 93, 22);

        jScrollPane20.setViewportView(nt);

        add(jScrollPane20);
        jScrollPane20.setBounds(579, 192, 93, 22);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       try{ 
        
         Pessoa ps = new Pessoa(nome.getText(),Double.parseDouble(cpf.getText()));
         ConexaoBancoDeDados cn = new ConexaoBancoDeDados();
         
         rg r = new rg();
         r.setNumero(Double.parseDouble(rg.getText()));
         
                /*Pessoa*/
         ps.setDataNasc(data_nc.getText());
         ps.setCpf(Double.parseDouble(cpf.getText()));
         ps.setNomePai(n_mae.getText());
         ps.setNomeMae(n_pai.getText());
         ps.setRg(r);
       
             /* Print */
         System.out.println(ps.getRg().getNumero());
         System.out.println(ps.getCpf());
         //conectar();
         cn.inserir(ps);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatorios!");
    }
    
    finally{
        JOptionPane.showMessageDialog(null,"ok");
     }
    
    
   }
    
    void commitBanco(){
                  
      ConexaoBancoDeDados db = new ConexaoBancoDeDados();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cpf;
    private javax.swing.JTextPane data_nc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane16;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private java.awt.Label label1;
    private javax.swing.JTextPane n_mae;
    private javax.swing.JTextPane n_pai;
    private javax.swing.JTextPane nome;
    private javax.swing.JTextPane nome1;
    private javax.swing.JTextPane nt;
    private javax.swing.JTextPane rg;
    // End of variables declaration//GEN-END:variables

}
